general_settings:
  master_key: sk-dummy # you can change this to any secret string you like

litellm_settings:
  drop_params: true

model_list:
  - model_name: claude-opus-4.6
    model_info:
      supports_vision: true
      max_input_tokens: 128000
      max_output_tokens: 16384
    litellm_params:
      model: github_copilot/gpt-5-mini
      drop_params: true
      extra_headers:
        editor-version: "vscode/1.116.0"

  - model_name: claude-sonnet-4.6
    model_info:
      supports_vision: true
      max_input_tokens: 128000
      max_output_tokens: 16384
    litellm_params:
      model: github_copilot/gpt-5-mini
      drop_params: true
      extra_headers:
        editor-version: "vscode/1.116.0"

  - model_name: claude-haiku-4.5
    model_info:
      supports_vision: true
      max_input_tokens: 128000
      max_output_tokens: 16384
    litellm_params:
      model: github_copilot/gpt-5-mini
      drop_params: true
      extra_headers:
        editor-version: "vscode/1.116.0"
